# WW3Tool one-line installer for Windows PowerShell (5.1+ / PowerShell 7+).
#
# Usage (run from PowerShell):
#   irm https://raw.githubusercontent.com/ZxyGch/WW3Tool/master/public/packaging/install.ps1 | iex
#
# Optional environment overrides (same names as the bash installer):
#   WW3TOOL_REPO_URL    Repo git URL (default: https://github.com/ZxyGch/WW3Tool.git)
#   WW3TOOL_INSTALL_DIR Install directory (default: $HOME\.ww3tool)
#   WW3TOOL_BIN_DIR     Directory for the ww3tool command wrapper
#                       (default: $HOME\.local\bin, or $HOME\bin if it exists)
#
# What it does: shallow-clones the repo into the install directory and writes a
# ww3tool.cmd wrapper (which calls run.py via python) into BIN_DIR. On first run,
# run.py creates a virtual environment and installs dependencies automatically.
#
# NOTE: do NOT use exit/param() here - the script is designed to be piped into
# `iex`, where `exit` would kill the caller's PowerShell session and `param()`
# is not allowed. Errors abort with `return` instead.

$ErrorActionPreference = "Stop"

if ($env:WW3TOOL_REPO_URL) { $RepoUrl = $env:WW3TOOL_REPO_URL } else { $RepoUrl = "https://github.com/ZxyGch/WW3Tool.git" }
if ($env:WW3TOOL_INSTALL_DIR) { $InstallDir = $env:WW3TOOL_INSTALL_DIR } else { $InstallDir = Join-Path $HOME ".ww3tool" }
if ($env:WW3TOOL_BIN_DIR) {
    $BinDir = $env:WW3TOOL_BIN_DIR
} else {
    $Candidate = Join-Path $HOME ".local\bin"
    $Alt = Join-Path $HOME "bin"
    if ((Test-Path $Candidate) -or ($env:PATH -split ";" | Where-Object { $_ -eq $Candidate })) {
        $BinDir = $Candidate
    } elseif (Test-Path $Alt) {
        $BinDir = $Alt
    } else {
        $BinDir = $Candidate
    }
}

Write-Host "==> WW3Tool installer (PowerShell)"
Write-Host "    repo:    $RepoUrl"
Write-Host "    install: $InstallDir"

# git is required
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Error "Error: 'git' is required. Install it from https://git-scm.com/download/win and re-run."
    return
}

$GitDir = Join-Path $InstallDir ".git"
if ((Test-Path $InstallDir) -and -not (Test-Path $GitDir)) {
    Write-Error "Error: $InstallDir exists but is not a WW3Tool repo (missing .git). Remove it or set WW3TOOL_INSTALL_DIR to another directory."
    return
}

if (-not (Test-Path $GitDir)) {
    Write-Host "==> Cloning repository (shallow)..."
    & git clone --depth 1 $RepoUrl $InstallDir
    if ($LASTEXITCODE -ne 0) { return }
} else {
    Write-Host "==> Updating existing installation..."
    Push-Location $InstallDir
    & git pull --ff-only
    if ($LASTEXITCODE -ne 0) {
        Write-Warning "Warning: update failed (local changes?). Please handle $InstallDir manually."
    }
    Pop-Location
}

if (-not (Test-Path (Join-Path $InstallDir "public\packaging\ww3tool"))) {
    Write-Error "Error: entry script 'ww3tool' not found in the repository (public\packaging\ww3tool)."
    return
}

# Pick the python command used by the wrapper: prefer `python`, fall back to the
# Windows Python launcher `py -3`.
$PythonCmd = "python"
& python --version *> $null
if ($LASTEXITCODE -ne 0) {
    $PythonCmd = "py -3"
    & py -3 --version *> $null
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Error: Python 3.9+ is required. Install it from https://www.python.org/downloads/ and re-run."
        return
    }
}

New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
$Wrapper = Join-Path $BinDir "ww3tool.cmd"
$CmdContent = "@echo off`r`n" +
              "rem WW3Tool launcher (Windows), generated by install.ps1`r`n" +
              "setlocal`r`n" +
              "set `"WW3TOOL_ROOT=$InstallDir`"`r`n" +
              "$PythonCmd `"%WW3TOOL_ROOT%\run.py`" %*`r`n" +
              "endlocal`r`n"
Set-Content -Path $Wrapper -Value $CmdContent -Encoding ASCII

Write-Host "==> Done."
Write-Host "    command: $Wrapper"
Write-Host "    First run creates a virtual environment and installs dependencies (a few minutes)."
if ($env:PATH -split ";" | Where-Object { $_ -eq $BinDir }) {
    Write-Host "    Note: $BinDir is already in PATH."
} else {
    Write-Host "    Note: add $BinDir to your PATH (user scope), then open a new terminal:"
    Write-Host "      [Environment]::SetEnvironmentVariable('Path', [Environment]::GetEnvironmentVariable('Path','User') + ';$BinDir', 'User')"
}
Write-Host "    Verify: ww3tool --help"
